precmd() { eval '$PROMPT_COMMAND' }

BG_COL_ESC='\033[1;100m'
BG_COL_RESET_ESC='\033[1;49m'
DECORATOR_COL_ESC='\033[1;37m'
FIELD_NAME_COL_ESC='\033[1;36m'
FIELD_VALUE_COL_ESC='\033[1;33m'
FG_COL_RESET_ESC='\033[1;'

# PROMPT_SUMMARY_STATS_STR=$'${BG_COL_ESC}${DECORATOR_COL_ESC}---=[ ${FIELD_NAME_COL_ESC}ret: ${FG_COL_RESET_ESC}\${PROMPT_SUMMARY_EXIT_CODE_COL_ESCOR}m\${PROMPT_SUMMARY_EXIT_CODE} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}user: ${FIELD_VALUE_COL_ESC}\${PROMPT_SUMMARY_FORMATED_TIME_USER} ${FIELD_NAME_COL_ESC}sys: ${FIELD_VALUE_COL_ESC}${PROMPT_SUMMARY_FORMATED_TIME_SYS} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}pid: ${FIELD_VALUE_COL_ESC}${$} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}tty: ${FIELD_VALUE_COL_ESC}\${PROMPT_SUMMARY_VARS[11]} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}shell: ${FIELD_VALUE_COL_ESC}\${PROMPT_SUMMARY_VARS[14]} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}hostname: ${FIELD_VALUE_COL_ESC}\${PROMPT_SUMMARY_VARS[12]} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}path: \${FIELD_VALUE_COL_ESC}\${PROMPT_SUMMARY_VARS[1]} ${DECORATOR_COL_ESC}]=$(get_fill_string)${BG_COL_RESET_ESC}\n$(tput sgr0)'

# PROMPT_SUMMARY_STATS_STR="${BG_COL_ESC}${DECORATOR_COL_ESC}---=[ ${FIELD_NAME_COL_ESC}ret: ${FG_COL_RESET_ESC}\${PROMPT_SUMMARY_EXIT_CODE_COL_ESC}\${PROMPT_SUMMARY_EXIT_CODE} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}user: ${FIELD_VALUE_COL_ESC}\${PROMPT_SUMMARY_FORMATED_TIME_USER} ${FIELD_NAME_COL_ESC}sys: ${FIELD_VALUE_COL_ESC}${PROMPT_SUMMARY_FORMATED_TIME_SYS} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}pid: ${FIELD_VALUE_COL_ESC}${$} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}tty: ${FIELD_VALUE_COL_ESC}\${PROMPT_SUMMARY_VARS[11]} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}shell: ${FIELD_VALUE_COL_ESC}\${PROMPT_SUMMARY_VARS[14]} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}hostname: ${FIELD_VALUE_COL_ESC}\${PROMPT_SUMMARY_VARS[12]} ${DECORATOR_COL_ESC}| ${FIELD_NAME_COL_ESC}path: \${FIELD_VALUE_COL_ESC}\${PROMPT_SUMMARY_VARS[1]} ${DECORATOR_COL_ESC}]=$(get_fill_string)${BG_COL_RESET_ESC}\n$(tput sgr0)"

# # PROMPT_SUMMARY_STATS="$(eval)"
# PROMPT_SUMMARY_STATS="${PROMPT_SUMMARY_STATS_STR}"

# echo "${PROMPT_SUMMARY_STATS}"
# echo "${PROMPT_SUMMARY_STATS_STR}"

PROMPT_SUMMARY_STATS=$'\033[1;100m\033[1;37m---=[ \033[1;36mret: \033[1;${PROMPT_SUMMARY_EXIT_CODE_COLOR}m$PROMPT_SUMMARY_EXIT_CODE \033[1;37m| \033[1;36muser: \033[1;33m${PROMPT_SUMMARY_VARS[77]} \033[1;36msys: \033[1;33m${PROMPT_SUMMARY_VARS[76]} \033[1;37m| \033[1;36mpid: \033[1;33m$$ \033[1;37m| \033[1;36mtty: \033[1;33m${PROMPT_SUMMARY_VARS[11]} \033[1;37m| \033[1;36mshell: \033[1;33m${PROMPT_SUMMARY_VARS[14]} \033[1;37m| \033[1;36mhostname: \033[1;33m${PROMPT_SUMMARY_VARS[12]} \033[1;37m| \033[1;36mpath: \033[1;33m${PROMPT_SUMMARY_VARS[1]} \033[1;37m]=$(get_fill_string)\033[1;49m\n$(tput sgr0)'

PROMPT="${PROMPT_SUMMARY_STATS}"
